CFLAGS=-g -O -Wall
hidosvm : hidosvm.c common.c common.h
	$(CC) $(CFLAGS) -o hidosvm hidosvm.c common.c -lx86emu
hidoskvm : hidoskvm.c common.c common.h
	$(CC) $(CFLAGS) -o hidoskvm hidoskvm.c common.c
